{% set name = "eventio" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 980559675c9462655b4e9c63add951a771dfa33e635913818238b823fb0e5598

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - pytest-runner
    - corsikaio 0.2.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - corsikaio 0.2.*
    - zstandard

test:
  imports:
    - eventio

about:
  home: https://github.com/cta-observatory/pyeventio
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Read-only python implementation of the eventio / sim_telarray data format

  description: |
    eventio is a read-only implementation of the eventio / sim_telarray data formats
    as produced by the CORSIKA iact extension and the sim_telarray software.
    Low-level access to eventio objects is supported as well as a higher
    level interface for sim_telarray and CORSIKA files.
  doc_url: https://github.com/cta-observatory/pyeventio
  dev_url: https://github.com/cta-observatory/pyeventio

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
